question START
	What is your biggest challenge for diet?
	-Snacking between meals#question cause_snack
	-Big meals#question cause_meal
end

question cause_meal
	What is the biggest cause of big meals for you?#breakfast_weekday_time
	-Stress#solution s8,s14
	-Finance#solution s6
	-Hunger
	-Loneliness#solution s8,s22,s29
	-Addiction to the food#solution s2,s3
	-Other
end

question cause_snack
	What is the biggest cause of snacking between meals for you?#snack_where
	-Stress#solution s8,s14,s15,s17,s22,s23,s29
	-Finance#solution s6,s13,s24
	-Hunger#solution s9,s19,s27
	-Loneliness#solution s8,s22,s9
	-Addiction to the food#solution s2,s3,s15,s17
	-Other
end

question breakfast_weekday_time
	When do you usually eat breakfast on weekdays?#lunch_weekday_time
	-Before 7:00 AM
	-7:00 AM - 8:30 AM
	-8:30 AM - 10:00 AM
	-After 10:00 AM
	-I don't eat breakfast on weekdays#solution s9,s27 
end

question lunch_weekday_time
	When do you usually eat lunch on weekdays?#dinner_weekday_time
	-Before 11:00 AM
	-11:00 AM - 12:00 PM
	-12:00 PM - 1:00PM
	-After 1:00 PM
	-I don't eat lunch on weekdays#solution s9
end

question dinner_weekday_time
	When do you usually eat dinner on weekdays?#breakfast_weekend_time
	-Before 5:00 PM
	-5:00 PM - 6:00 PM
	-6:00 PM - 7:00 PM
	-After 7:00 PM#solution s16,s18,s28
	-I don't eat dinner on weekdays#solution s9,s19
end

question breakfast_weekend_time
	When do you usually eat breakfast on weekends?#lunch_weekend_time
	-Before 7:00 AM
	-7:00 AM - 8:30 AM
	-8:30 AM - 10:00 AM
	-After 10:00 AM
	-I don't eat breakfast on weekends#solution s9,s27 
end

question lunch_weekend_time
	When do you usually eat lunch on weekends?#dinner_weekend_time
	-Before 11:00 AM
	-11:00 AM - 12:00 PM
	-12:00 PM - 1:00PM
	-After 1:00 PM
	-I don't eat lunch on weekends#solution s9
end

question dinner_weekend_time
	When do you usually eat dinner on weekends?#track
	-Before 5:00 PM
	-5:00 PM - 6:00 PM
	-6:00 PM - 7:00 PM
	-After 7:00 PM#solution s16,s18,s28
	-I don't eat dinner on weekends#solution s9,s19
end

question track
	Do you track what you eat for meals?
	-Yes#question track_how
	-No#question eat_out_lunch#solution s5,s18,s21
end

question track_how
	How do you track your meals?#track_when
	-Write it down#solution s5
	-Using an app
end
	
question track_when
	How often do you track your meals?#eat_out_lunch
	-Less than once a week
	-1 to 3 times a week
	-4 to 6 times a week
	-Everyday
end

question eat_out_lunch
	How often do you go out for lunch?#eat_out_lunch_why
	-Less than once a week
	-1 to 3 times a week
	-4 to 6 times a week
	-Everyday
end

question eat_out_lunch_why
	Why do you eat out for lunch?#eat_out_dinner
	-Food Preference
	-No time to prepare lunch#solution s10,s11,s18,s19
	-Not interested in cooking
	-Convenience#solution s10,s11,s18,s19
	-Other
end

question eat_out_dinner
	How often do you go out for dinner?#eat_out_dinner_why
	-Less than once a week
	-1 to 3 times a week
	-4 to 6 times a week
	-Everyday
end

question eat_out_dinner_why
	Why do you eat out for dinner?#do_cook
	-Food Preference
	-No time to prepare dinner
	-Not interested in cooking
	-Convenience#solution s10,s11,s18,s19
	-Other
end

question do_cook
	Do you cook at home?#shopping
	-Yes#solution s20,s10
	-No#solution s11
end

question snack_where
	Where do you usually eat snacks?#snack_when
	-At work
	-At home
	-Outside
	-Social Settings
	-Other
end

question snack_when
	When do you usually eat snacks?#snack_activity
	-Early morning
	-Late morning
	-Afternoon
	-Evening#solution s9,s19,s27
end

question snack_activity
	What do you usually do while snacking?#snack_type
	-Chat#solution s1
	-Watch T.V.#solution s1
	-Work#solution s1
	-Read#solution s1
	-Listen to music#solution s1
	-Surf the internet#solution s1
	-Nothing else#solution s1
	-Other#solution s1
end

question snack_type
	What kind of snack do you usually eat?#track_snack
	-Cookies#solution s1,s7,s3
	-Fruits
	-Ice cream#solution s1,s7,s3
	-Nuts
	-Chips#solution s1,s7,s3
	-Candy#solution s1,s7,s3
	-Cheese#solution s1,s7,s3
	-Other
end

question track_snack
	Do you track what you eat for snacks?
	-Yes#question track_snack_how
	-No#question shopping#solution s5,s18,s21
end

question track_snack_how
	How do you track your snacks?#track_snack_when
	-Write it down#solution s5
	-Using an app
end
	
question track_snack_when
	How often do you track your snacks?#shopping
	-Less than once a week
	-1 to 3 times a week
	-4 to 6 times a week
	-Everyday
end

question shopping
	Do you do the food shopping?
	-Yes#question shopping_often
	-No#question drinks
end

question shopping_often
	How often do you shop for food groceries?#shopping_budget
	-Less than once a month
	-Once a month
	-2-3 times a month
	-Weekly
	-More than once a week
end

question shopping_budget
	Do you have a budget for your shopping?#shopping_plan
	-Yes
	-No
end

question shopping_plan
	Do you plan for your shopping list before you go?
	-Yes#question shopping_plan_follow
	-No#question drinks#solution s13
end

question shopping_plan_follow
	Will you buy the food exactly based on your shopping list?
	-Yes#question drinks
	-No#solution s13#question shopping_plan_follow_why
end

question shopping_plan_follow_why
	What drives you to buy the food not on your list?#drinks
	-Discounts
	-Advertisement
	-Recommendation
	-Coupon
	-The food itself
	-Others
end


question drinks
	What do you usually have for drink?#DONE
	-Water
	-Tea
	-Coffee
	-Soft Drinks
	-Juice
	-Milk
	-Other
end

solution s1
	Replace snack with a lower calorie healthier option
end

solution s2
	Avoid grocery store aisles with unhealthy foods
end

solution s3
	Reduce the portion of the snack you eat by a small increment
end

solution s4
	Change the snacking time to the morning.
end

solution s5
	Use a paper journal or mobile app  such as "My fitness pal' to track your diet so you can find out if you are eating more than you are burning
end

solution s6
	Go to a warehouse store like Sam's Club to save money on healthy snacks
end

solution s7
	Buy or prepare single servings of snacks
end

solution s8
	Reward yourself for completing a week of diet tracking 
end

solution s9
	To prevent extreme hunger, make a plan to avoid going more than 3-4 hours without eating 
end

solution s10
	Pack dinner leftovers for lunch.
end

solution s11
	Start to cook meals at home.
end

solution s12
	Set up a budget for your shopping.
end

solution s13
	Make and stick to a shopping list  
end

solution s14
	Before eating when stressed, take 10 deep breaths and see if craving passes
end

solution s15
	Gradually reduce the amount of sugar in your diet
end

solution s16
	Rearrange your schedule to eat dinner sooner.
end

solution s17
	Increase the amount of fiber and protein in your diet to suppress your appetite
end

solution s18
	Track your intake on at least 1-2 days per week 
end

solution s19
	Find healthy frozen meals that are quick to prepare instead of fast food
end

solution s20
	Only cook the exact portions needed for that meal
end

solution s21
	Track your intake after 2pm only instead of all day
end

solution s22
	Call a friend to talk about what's stressing you instead of eating
end

solution s23
	Go for a short walk when you feel stressed instead of eating
end

solution s24
	Do a Google search for "healthy canned foods" for ideas of inexpensive healthy foods
end

solution s26
	Plan snacks at the beginning of each day. Stick to that plan.
end

solution s27
	Buy on-the-go breakfast items (e.g., nutrition shake, nutrition bar)
end

solution s28
	Brush and floss when you are done eating for the day to prevent further eating
end

solution s29
	Find a weight loss buddy to get extra support
end
