question START
	Do you track what you eat?#problem_meal
	-Yes#solution s8
	-No#solution s5,s18,s21
end

question problem_meal
	Do you eat too much and/or make unhealthy choices at meals?#problem_snack
	-Yes#question meal_why
	-No#question problem_snack
end

question meal_why
	What makes you eat too much at meals?#problem_snack
	-Stress#solution s3,s14,s22
	-Junk food is cheap#solution s24
	-Hunger#solution s9,s17
	-Boredom
end

question problem_snack
	Do you snack too much and/or make unhealthy snack choices?#overeat_when
	-Yes#question snack_why
	-No#question overeat_when
end

question snack_why
	What makes you snack too much?#overeat_when
	-Stress#solution s3,s14,s22
	-Junk food is cheap#solution s6,s24
	-Hunger#solution s9,s17
	-Boredom
end

question overeat_when
	On which occasions do you overeat on mainly?#weekday_breakfast
	-Parties#solution s49,s52
	-Restaurants#solution s53
	-Social Events#solution s54
	-Weekends#solution s55
	-None
end

question weekday_breakfast
	On weekdays,#weekend_breakfast
	-I always have breakfast
	-I never have breakfast#solution s27
	-I mostly have breakfast
	-I rarely have  breakfast#solution s27
end

question weekend_breakfast
	On weekends,#cravings
	-I always have breakfast
	-I never have breakfast#solution s27
	-I mostly have breakfast
	-I rarely have  breakfast#solution s27
end

question cravings
	Do you have food cravings?#cook
	-Yes#solution s15,s33,s34,s35
	-No
end

question cook
	Do you cook dinner at home?
	-Yes#solution s20#question pack
	-No#solution s11,s19#question cook_why
end

question cook_why
	Why do you not cook?#family_cook
	-No time for cooking#solution s19
	-I don't know how#solution s39,s44
	-I don't have food at home to cook#solution s11,s13,s4
end

question family_cook
	Does someone else in your family cook?#pack
	-Yes#solution s36
	-No#solution s30
end

question pack
	Do you pack your lunch for work or school?#snack_where
	-Yes#solution s42
	-No#solution s10
end


question snack_where
	Where do you usually eat snacks?#snack_when
	-At work#solution s40
	-At home#solution s32
	-In the car#solution s39
	-Social Settings#solution s41
	-Other
end

question snack_when
	When do you usually eat snacks?#snack_activity
	-Early morning#solution s38
	-Late morning#solution s38
	-Afternoon#solution s4,s38
	-Evening#solution s4,s9,s19,s27,s28,s38
	-Late at night#solution s4,28,s38
end

question snack_activity
	What do you usually do while snacking?#snack_type
	-Chat#solution s37
	-Watch T.V.#solution s32
	-Work#solution s38
	-Read#solution s38
	-Listen to music#solution s38
	-Surf the internet#solution s38
	-Drive#solution s38
	-Other#solution s39
end

question snack_type
	What kind of snack do you usually eat?#shopping
	-Cookies#solution s1,s7,s3,s15
	-Fruits#solution s15
	-Ice cream#solution s1,s7,s3,s15
	-Nuts
	-Chips#solution s1,s7,s3,s15
	-Candy#solution s1,s7,s3,s15
	-Cheese#solution s1,s7,s3,s15
	-Other
end

question shopping
	Do you do the food shopping?
	-Yes#solution s13#question shopping_often
	-No#question drinks
end

question shopping_often
	How often do you shop for food groceries?#shopping_budget
	-Less than once a month#solution s25
	-Once a month#solution s25
	-2-3 times a month
	-Weekly
	-More than once a week
end

question shopping_budget
	Do you have a budget for your shopping?#shopping_plan
	-Yes
	-No#solution s12
end

question shopping_plan
	Do you plan for your shopping list before you go?
	-Yes#question shopping_plan_follow
	-No#question drinks#solution s13
end

question shopping_plan_follow
	Will you buy the food exactly based on your shopping list?
	-Yes#question drinks
	-No#solution s13,s2#question shopping_plan_follow_why
end

question shopping_plan_follow_why
	What drives you to buy the food not on your list?#drinks
	-Discounts#solution s12
	-Forgot to put on my list
	-Recommendations from others
	-Family members#solution s46
	-Food looks tempting#solution s47,s2
	-Other
end

question drinks
	What do you usually have for drink?#DONE
	-Water
	-Tea#solution s48
	-Coffee#solution s31
	-Soft Drinks#solution s31
	-Juice
	-Milk
	-Other
end

solution s1
	Replace snack with a lower calorie healthier option
end

solution s2
	Avoid grocery store aisles with unhealthy foods
	info|http://www.diabeticlivingonline.com/food-to-eat/nutrition/tips-healthy-shopping-grocery-store
end

solution s3
	Reduce the portion of the snack you eat by a small increment
	info|http://www.fudiet.com/2012/02/overcoming-emotional-eating/
end

solution s4
	Change the snacking time to the morning.
end

solution s5
	Use a paper journal or mobile app  such as "My fitness pal' to track your diet so you can find out if you are eating more than you are burning
	info|http://www.fudiet.com/2014/02/why-do-i-need-to-track-calories-to-lose-weight/
end

solution s6
	Go to a warehouse store like Sam's Club to save money on healthy snacks
end

solution s7
	Buy or prepare single servings of snacks
end

solution s8
	Reward yourself for completing a week of diet tracking
	info|http://www.fudiet.com/2012/08/5-ways-to-make-diet-journaling-easier/
end

solution s9
	To prevent extreme hunger, make a plan to avoid going more than 3-4 hours without eating 
end

solution s10
	Pack dinner leftovers for lunch.
end

solution s11
	Start to cook meals at home.
	info|http://www.choosemyplate.gov/weight-management-calories/weight-management/better-choices/cook-home.html
end

solution s12
	Set up a budget for your shopping.
	info|http://www.eatright.org/Public/content.aspx?id=6442463962
end

solution s13
	Make and stick to a shopping list  
end

solution s14
	Before eating when stressed, take 10 deep breaths and see if craving passes
	info|http://www.fudiet.com/2012/02/overcoming-emotional-eating/
end

solution s15
	Gradually reduce the amount of sugar in your diet
	info|http://www.fudiet.com/2011/07/how-to-get-over-your-sugar-addiction/
end

solution s16
	Rearrange your schedule to eat dinner sooner.
end

solution s17
	Increase the amount of fiber and protein in your diet to suppress your appetite
	info|http://healthyeating.sfgate.com/protein-fiber-work-together-1317.html
end

solution s18
	Track your intake on at least 1-2 days per week 
	info|http://www.fudiet.com/2012/08/5-ways-to-make-diet-journaling-easier/
end

solution s19
	Find healthy frozen meals that are quick to prepare instead of fast food
	info|http://www.webmd.com/food-recipes/features/best-frozen-dinners
end

solution s20
	Only cook the exact portions needed for that meal
end

solution s21
	Track your intake after 2pm only instead of all day
	info|http://www.fudiet.com/2012/08/5-ways-to-make-diet-journaling-easier/
end

solution s22
	Call a friend to talk about what's stressing you instead of eating
	info|http://www.fudiet.com/2012/02/overcoming-emotional-eating/
end

solution s23
	Go for a short walk when you feel stressed instead of eating
	info|http://www.fudiet.com/2012/02/overcoming-emotional-eating/
end

solution s24
	Do a Google search for "healthy canned foods" for ideas of inexpensive healthy foods
end

solution s25
	Don't buy snack items in bulk, get them in smaller portions at the store
end

solution s27
	Buy on-the-go breakfast items (e.g., nutrition shake, nutrition bar)
end

solution s28
	Brush and floss when you are done eating for the day to prevent further eating
end

solution s30
	Go online to find some recipes which are healthy and easy to get started.
	info|http://www.cookinglight.com/
end

solution s31
	Drink water instead of sugary beverages.
end

solution s32
	Do an activity that would be difficult to eat during (e.g., knitting, light exercise, anything that occupies hands)
end

solution s33
	Don't keep foods that generate cravings in the home.
end

solution s34 
	Distract yourself for 15 minutes to allow time for the craving to pass
end

solution s35
	Try a healthy food to satisfy your craving (for example have berries if craving sweets)
end

solution s36
	Ask the person who cooks to make healthy dishes/provide them with healthy recipes
	info|http://www.cookinglight.com/
end	

solution s37
	Take a walk when you talk on the phone
end

solution s38
	Set specific times that you can have a snack to prevent snacking outside of those times
end

solution s39
	Plan to have healthy snacks in the car, especially during commute or long drives
end

solution s40
	Bring one day of healthy snacks to work with you each day
end

solution s41
	Bring healthy snacks to parties and other social gatherings
end

solution s42
	Make a list of healthy lunch options to add to the grocery list (e.g., frozen meals, salads, sandwiches)
end

solution s43
	Bring something quick to eat for lunch (e.g., protein shake, meal bar) to prevent yourself from skipping it
end

solution s44
	Take a healthy cooking class via community center or Whole Foods Market
end

solution s45
	Set a regular time each week to go grocery shopping
end

solution s46
	If family members insist on buying junk food, ask them to buy kinds you do not like
	info|http://www.fudiet.com/2012/03/help-im-surrounded-by-people-who-eat-junk-food/
end

solution s47
	Go grocery shopping directly after a meal so you are better able to resist temptations
end

solution s48
	Reduce amount of cream, milk and sugar in your coffee/tea
end

solution s49
	Bring a veggie tray or other healthy dish to parties 
end

solution s50
	Eat something small before going out to eat or to a party to control appetite
end

solution s51
	Drink a glass of water in between alcoholic beverages to limit alcohol intake and additional eating
end

solution s52
	Makeover unhealthy holiday/party foods that you tend to overeat every time
end

solution s53
	Avoid restaurants where you always overeat. Go to ones where you have shown better control.
end

solution s54
	During social events, make sure you have a low cal food like fruit or veggies to graze on.
end

solution s55
	Track your diet on weekends to become more aware of your weekend intake
end
